<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ApplicationIcon>icon.ico</ApplicationIcon>
    <AssemblyName>TList</AssemblyName>
    <RootNamespace>TList</RootNamespace>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishTrimmed>true</PublishTrimmed>
    <TrimMode>link</TrimMode>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Photino.NET" Version="4.*" />
  </ItemGroup>

  <ItemGroup>
    <None Update="icon.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <Target Name="CopyHtml" AfterTargets="Build">
    <Exec Command="copy /Y &quot;$(ProjectDir)..\TList.html&quot; &quot;$(OutputPath)TList.html&quot;" />
  </Target>
  <Target Name="CopyHtmlPublish" AfterTargets="Publish">
    <Exec Command="copy /Y &quot;$(ProjectDir)..\TList.html&quot; &quot;$(PublishDir)TList.html&quot;" />
  </Target>

</Project>
